### PR TITLE
Special error message for removing from empty history

### LINKED ISSUE #78: Incorrect error message when removing message from empty messageHistory
When I try to remove a message from an empty messageHistory, the error message is technically incorrect:

``` matlab
>> messages = messageHistory;
>> removeMessage(messages,1)
Error using messageHistory/removeMessage (line 217)
Index exceeds the number of array elements. Index
must be less than or equal to 0.
```

### PR DESCRIPTION
**Pull request by ccreutzi**
Fixes #78

### CODE REVIEW

File: +llms/+utils/errorMessageCatalog.m [hunk 1]
```diff
@@ -42,6 +42,7 @@
 catalog("llms:mustBeAssistantWithNameAndArguments") = "Field 'function' must be a struct with fields 'name' and 'arguments'.";
 catalog("llms:assistantMustHaveTextNameAndArguments") = "Fields 'name' and 'arguments' must be text with one or more characters.";
 catalog("llms:mustBeValidIndex") = "Index exceeds the number of array elements. Index must be less than or equal to {1}.";
+catalog("llms:removeFromEmptyHistory") = "Cannot remove message from empty message history.";
```
Comment (MiriamScharnke) [inline +llms/+utils/errorMessageCatalog.m:45]:
```suggestion
catalog("llms:removeFromEmptyHistory") = "Unable to remove message from empty message history.";
```

**Review by MiriamScharnke — APPROVED** [review]

**Review by adulai — APPROVED** [review]

**Review by vpapanasta — APPROVED** [review]
